#!/bin/sh
#
# Last Modified: 2025-Nov-09
#
# shellcheck disable=SC1091
# shellcheck disable=SC2034
# shellcheck disable=SC2086
#
if [ -f /opt/etc/init.d/S32vnstat ]
then
	/opt/etc/init.d/S32vnstat stop >/dev/null 2>&1
	sleep 2 ; killall -q vnstatd ; sleep 1
fi
if [ -f /opt/etc/init.d/S32vnstat2 ]
then
	/opt/etc/init.d/S32vnstat2 stop >/dev/null 2>&1
	sleep 2 ; killall -q vnstatd ; sleep 1
fi
rm -f /opt/etc/init.d/S32vnstat
rm -f /opt/etc/init.d/S32vnstat2

if [ -f "/opt/share/dn-vnstat.d/config" ]
then
	SCRIPT_STORAGE_DIR="/opt/share/dn-vnstat.d"
else
	SCRIPT_STORAGE_DIR="/jffs/addons/dn-vnstat.d"
fi

TZ=$(cat /etc/TZ)
export TZ

SCRIPT_NAME="vnstat"

ENABLED=yes
PROCS=vnstatd
ARGS="-d --noadd --config $SCRIPT_STORAGE_DIR/vnstat.conf"
PREARGS=""
DESC="$PROCS"
PATH=/opt/sbin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

##----------------------------------------##
## Modified by Martinski W. [2025-Nov-09] ##
##----------------------------------------##
if [ "$1" = "start" ] || [ "$1" = "restart" ]
then
	if [ -f "$SCRIPT_STORAGE_DIR/vnstat.conf" ]
	then
		IFACE="$(grep "Interface " "$SCRIPT_STORAGE_DIR/vnstat.conf" | awk '{print $2}' | sed 's/"//g')"
		logger -st "${SCRIPT_NAME}_[$$]" "Starting monitoring for interface $IFACE"
	else
		logger -st "${SCRIPT_NAME}_[$$]" "Configuration file missing - $SCRIPT_STORAGE_DIR/vnstat.conf - please check"
		exit 1
	fi
	if [ "$(nvram get ntp_ready)" -eq 0 ]
	then
		logger -st "${SCRIPT_NAME}_[$$]" "NTP not synced, exiting"
		exit 1
	fi

	if ! vnstat --config "$SCRIPT_STORAGE_DIR/vnstat.conf" -i "$IFACE" >/dev/null 2>&1
	then
		vnstatd $ARGS >/dev/null 2>&1
		vnstat --config "$SCRIPT_STORAGE_DIR/vnstat.conf" --add -i "$IFACE" >/dev/null 2>&1
		killall -q vnstatd >/dev/null 2>&1
	fi
fi

. /opt/etc/init.d/rc.func
